# compile cosmovisor
FROM golang:1.21.4-alpine3.18 as builder

RUN apk add --no-cache git build-base linux-headers

WORKDIR /app

COPY . .

RUN go env -w GO111MODULE=on && cd /app/tools/cosmovisor && go mod download && make cosmovisor

FROM functionx/fx-core:6.0.0 as fxv6
FROM functionx/fx-core:7.0.1-rc0 as fxv7
FROM functionx/fx-core:7.1.0-rc1 as fxv7_1
FROM functionx/fx-core:7.2.0-rc2 as fxv7_2

# build fxcorevisor
FROM alpine:3.18

WORKDIR root

ENV DAEMON_HOME=/root/.fxcore
ENV DAEMON_NAME=fxcored

# optional
ENV DAEMON_ALLOW_DOWNLOAD_BINARIES=false
ENV DAEMON_RESTART_AFTER_UPGRADE=true
ENV DAEMON_RESTART_DELAY=1s
ENV DAEMON_POLL_INTERVAL=3s
ENV DAEMON_DATA_BACKUP_DIR=/root/.fxcore
ENV UNSAFE_SKIP_BACKUP=true
ENV DAEMON_PREUPGRADE_MAX_RETRIES=3

ENV DAEMON_CHOOSE_VERSION=true
ENV DAEMON_COSMOVISOR_REPLACE=true
ENV DAEMON_BINARY_PATH=/cosmovisor/binary
ENV DAEMON_UPGRADES_INFO_PATH=/cosmovisor/upgrades-info

RUN mkdir -p /cosmovisor/binary/genesis/bin && \
    mkdir -p /cosmovisor/binary/upgrades/v7.0.x/bin && \
    mkdir -p /cosmovisor/binary/upgrades/v7.1.x/bin && \
    mkdir -p /cosmovisor/binary/upgrades/v7.2.x/bin

COPY --from=builder /app/tools/cosmovisor/upgrades-info/v7.0.x /cosmovisor/upgrades-info
COPY --from=builder /app/tools/cosmovisor/upgrades-info/v7.1.x /cosmovisor/upgrades-info
COPY --from=builder /app/tools/cosmovisor/upgrades-info/v7.2.x /cosmovisor/upgrades-info

COPY --from=fxv6 /usr/bin/fxcored /cosmovisor/binary/genesis/bin
COPY --from=fxv7 /usr/bin/fxcored /cosmovisor/binary/upgrades/v7.0.x/bin
COPY --from=fxv7_1 /usr/bin/fxcored /cosmovisor/binary/upgrades/v7.1.x/bin
COPY --from=fxv7_2 /usr/bin/fxcored /cosmovisor/binary/upgrades/v7.2.x/bin

COPY --from=builder /app/tools/cosmovisor/cosmovisor /usr/bin/cosmovisor

EXPOSE 26656/tcp 26657/tcp 26660/tcp 9090/tcp 1317/tcp 8545/tcp 8546/tcp

VOLUME ["/root"]

ENTRYPOINT ["cosmovisor"]
